name: Gatsby Publish on Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat << EOF >> .env
          INSTA_API_KEY=${{ secrets.INSTA_API_KEY }}
          EOF
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
