name: Gatsby Publish on Push

on:
  repository_dispatch:
      types: [build]
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    env: 
      INSTA_API_KEY: ${{ secrets.INSTA_API_KEY }}
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          
