name: Gatsby Publish on Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        env:
          INSTA_API_TOKEN: ${{ secrets.INSTA_API_TOKEN }}
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          
